### ISSUE TITLE
Request: GTK4 on MassOS

### ISSUE THREAD

**Issue by AaronTechnic** [TheSonicMaster/MassOS#12]
Since GTK apps are porting to GTK4, I think it might be a good idea to include it by default on MassOS.

Here are the commands that I used to install:

```
wget https://ftp.acc.umu.se/pub/gnome/sources/gtk/4.5/gtk-4.5.1.tar.xz # Download
tar -xf gtk-4.5.1.tar.xz # Extract
cd gtk-4.5.1 # change dir
mkdir build && cd build # prepare build dir
meson --prefix=/usr --buildtype=release -Dbroadway-backend=true -Dtracker=enabled # compile, tracker enables search in file picker, but requires the tracker package
ninja # build
ninja install # install
cd ../.. # change to previous dir
```

**Comment by TheSonicMaster** [comment]
There are currently no programs in MassOS which require GTK4. Flatpak programs which require it will use the GNOME runtime which includes GTK4. GTK4 support is a possibility in the future, but I don't plan to include it until some programs in MassOS depend on it.

For GTK4 support, we also need to make sure the MassOS theme (Arc) is supported and enabled with it. In the latest version of the Arc theme, GTK4 is supported, however enabling it in GTK4 programs may need extra configuration files.

Lastly, it may be necessary to edit the build flags passed to Meson. `-Dtracker=enabled` is only necessary for GNOME, Xfce doesn't use Tracker, and if Tracker must be installed, it might require installing additional GNOME-specific dependencies which we don't want/need for Xfce. You can also add the flags `-Dcolord=enabled -Dsysprof=enabled -Dmedia-gstreamer=enabled -Dmedia-ffmpeg=enabled` to add support for more features which MassOS already provides the necessary dependencies for.

**Comment by AaronTechnic** [comment]
Got it. Thanks.
