### ISSUE TITLE
Baby Shark

### ISSUE THREAD

**Issue by IKGissmart** [TheSonicMaster/MassOS#3]
Pinkfong
Pinkfong

(Shark family)
(상어 가족)
baby shark turu lulu
아기 상어 뚜루루 뚜루

cute turu lulu
귀여운 뚜루루 뚜루

True in the sea
바닷속 뚜루루 뚜루

Baby Shark!
아기 상어!
mama shark turu lulu
엄마 상어 뚜루루 뚜루

Pretty tuluru turu
어여쁜 뚜루루 뚜루

True in the sea
바닷속 뚜루루 뚜루

Mama Shark!
엄마 상어!
Daddy Shark
아빠 상어 뚜루루 뚜루

The strong TRUE TRUE TRUE
힘이 센 뚜루루 뚜루

True in the sea
바닷속 뚜루루 뚜루

Daddy Shark!
아빠 상어!
Grandma Shark (True, True, True)
할머니 상어 (뚜루루 뚜루)

Caring (True, True, True)
자상한 (뚜루루 뚜루)

True in the sea
바닷속 뚜루루 뚜루

Grandma Shark!
할머니 상어!
Grandpa Shark (True Lou True)
할아버지 상어 (뚜루루 뚜루)

Cool (True, True, True)
멋있는 (뚜루루 뚜루)

True in the sea
바닷속 뚜루루 뚜루

Grandpa Shark!
할아버지 상어!
We are tullu tulu
우리는 뚜루루 뚜루

tuluru turu of the sea
바다의 뚜루루 뚜루

hunter turu lulu
사냥꾼 뚜루루 뚜루

Shark family!
상어 가족!
It's a shark
상어다 뚜루루 뚜루

Run away
도망쳐 뚜루루 뚜루

Run away
도망쳐 뚜루루 뚜루

Let's hide! Ahh!
숨자! 으악!
I lived, true, true, true
살았다 뚜루루 뚜루

I lived, true, true, true
살았다 뚜루루 뚜루

Today too
오늘도 뚜루루 뚜루

Lived!
살았다 휴!
I'm excited (True, true, true)
신난다 (뚜루루 뚜루)

I'm excited (True, true, true)
신난다 (뚜루루 뚜루)

Dancing tul lu lu luo
춤을 춰 뚜루루 뚜루

End of the song! Oh yeah!
노래 끝! 오예!

**Comment by PaintedAmdree** [comment]
Please stop.

**Comment by AaronTechnic** [comment]
nice song
