### ISSUE TITLE
[Feature Request]:  give package manager pls

### ISSUE THREAD

**Issue by ghost** [TheSonicMaster/MassOS#49]
### Checklist

- [X] I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my feature request has not already been reported.
- [X] If I am suggesting the addition of a program, the program is free software and licensed under a [GPL-compatible license](https://www.gnu.org/licenses/license-list.html).

### Suggestion

man no package manager kind of sucks no cap 🧢🧢🧢🧢🧢

**Comment by Bortus-AI** [comment]
You can use flatpak, homebrew and snapd

**Comment by ghost** [comment]
> 
They suck balls

**Comment by AaronTechnic** [comment]
Masspkg is still in development.

**Comment by AaronTechnic** [comment]
I'm speechless too.
