### ISSUE TITLE
Update MassOS screenshots

### ISSUE THREAD

**Issue by AaronTechnic** [TheSonicMaster/MassOS#9]
This isn't exactly an _issue_, but the screenshots are using the old font, and not Noto Sans Regular.

**Comment by TheSonicMaster** [comment]
Fixed in https://github.com/TheSonicMaster/MassOS/commit/64ab3c2250639888f1170f7ca3284a6504809aee.

Changes in the development branch are not merged into the main branch until the next release of MassOS.
